services:

  koha:
    image: fabianbaena/koha-eib:1.3
    container_name: koha
    cap_add:
      - SYS_NICE
      - DAC_READ_SEARCH
    depends_on:
      - koha-db
    environment:
      DB_HOST: koha-db
      DB_ROOT_PASSWORD: secret
      KOHA_TRANSLATE_LANGUAGES: "es-ES"
      INTRAPORT: 8080
    ports:
      - "80:80"
      - "8080:8080"

  koha-db:
    image: mariadb:10.3
    container_name: koha-db
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - koha-db-data:/var/lib/mysql

  memcached:
    image: memcached
    container_name: memcached
    command: memcached -m 64m

volumes:
  koha-db-data:
